### ISSUE TITLE
Socket keeps disconnecting

### ISSUE THREAD

**Issue by HerveZu** [GimliCZ/TwitchEventSub_Websocket#12]
When I start the client everything runs fine.

```
[12:32:06 INF] [EventSubClient] - [EventSubscriptionManager]  Event Sub ready: Client Id: ** accessToken ** session **
[12:32:07 INF] [EventSubClient] - [EventSubscriptionManager] Cleared subscription:stream.online
[12:32:08 INF] [EventSubClient] - [EventSubscriptionManager] Cleared subscription:channel.chat.message
[12:32:09 INF] [EventSubClient] - [EventSubscriptionManager] Added extra sub: stream.online
[12:32:09 INF] [EventSubClient] - [EventSubscriptionManager] Added extra sub: channel.chat.message
[12:32:09 INF] [EventSubClient] - [EventSubscriptionManager] Check run.
```

However, after 2 minutes the `OnUnexpectedConnectionTermination` event is fired with the message `[EventSubClient] - [Watchdog] Server didn't respond in time`. Then I disconnect and connect again the client and all of this happens again and again.

**Comment by HerveZu** [comment]
It's not always happening, but fairly often.

**Comment by GimliCZ** [comment]
I will try to investigate. It might be an issue with missbehavior of watchdog.
As documentation states: keep alive message and notification are the only sources of resets of keep alive connection.
Ping is totaly separate and while reconnecting the watch dog is restarted automatically.
It might be I read something wrong or there might be some other issue... 
[https://dev.twitch.tv/docs/eventsub/handling-websocket-events/](url)

Event sub client is sensitive on timing and its best to have it somewhere out of heavy tasks. 
Optionaly separate thread.
The best option might be separate background service.

**Comment by HerveZu** [comment]
I need to spin up new client dynamically, they run in the main thread but every callbacks is non blocking (.ConfigureAwait(false))

**Comment by HerveZu** [comment]
Same issue when I don't have any event handlers set

**Comment by GimliCZ** [comment]
> I need to spin up new client dynamically, they run in the main thread but every callbacks is non blocking (.ConfigureAwait(false))

Deactivation of synchronization context and creation of new thread by it is good solution. 
You can try to provide faster comunication using EventSubClientOptions
So far, as I tested the basic follow subscription, the program run correctly. 

Next week I will push update with direct access to websocket messaging for better debuging.

**Comment by GimliCZ** [comment]
#14 Should help diagnose issue.

**Comment by GimliCZ** [comment]
With last few updates, regarding exposure of raw messaging. #15 
Expansion of diagnostics and fixes of websocket and events you should be able to diagnose problem.
Happy hunting.

**Comment by GimliCZ** [comment]
We have probably found the issue. 
Sometimes there would be multiple messages within buffer. Solution will me in PR and friday it will be added to nuget.
