### ISSUE TITLE
Add ChannelChatMessage event

### ISSUE THREAD

**Issue by HerveZu** [GimliCZ/TwitchEventSub_Websocket#9]
I see that `ChannelChatMessage` event is implemented yet there's no public event for it.

I'd love to create a PR for that but I'm not able to create a new branch.

Changes to do
```cs
// EventSubClient.cs

public event AsyncEventHandler<ChannelChatMessage> OnChannelChatEventAsync; 

// Inside SocketOnNotificationAsync
case ChannelChatMessage channelChatMessage:
    await OnChannelChatEventAsync.TryInvoke(sender, channelChatMessage);
    break;
```

**Comment by HerveZu** [comment]
Also in `CreateSubscriptionRequestExtensions.cs` this line should be updated

```cs
{
        SubscriptionType.ChannelChatMessage,
        ("channel.chat.message", "1", CreateSubscriptionRequestExtension.CondList(ConditionType.BroadcasterUserId, ConditionType.UserId)) // <-- added ConditionType.UserId
},
```

**Comment by GimliCZ** [comment]
Thank you for pointing out mistakes.
I have known about this issue for quite a while, but I didnt have enough time to resolve it.
Update on the way.

**Comment by HerveZu** [comment]
Thanks you @GimliCZ . Btw I really like your lib, keep up the great work 💪

**Comment by HerveZu** [comment]
@GimliCZ You forgot to update the interface, my bad I didn't write it either. Also you didn't remove the previous 
```cs
{
        SubscriptionType.ChannelChatMessage,
        ("channel.chat.message", "1", CreateSubscriptionRequestExtension.CondList(ConditionType.BroadcasterUserId))
},
```
causing a duplicate key exception

**Comment by GimliCZ** [comment]
Hi again.
Sorry, I didn't check it more. I didn't have strenght to run it in test enviroment,
Litterarly got ill while writing it. 🤒

#11 
Event exposed
Dupe fixed
